//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForm.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderID { get; set; }
        public string Email { get; set; }
        public Nullable<int> Id { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
        public virtual Product Product { get; set; }
    }
}
